name: Terraform Deploy

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Cache Terraform modules
        uses: actions/cache@v3
        with:
          path: ~/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan AWS
        run: terraform plan -target=module.aws

      - name: Terraform Apply AWS
        run: terraform apply -target=module.aws -auto-approve

      - name: Terraform Plan Helm
        run: terraform plan -target=module.helm

      - name: Terraform Apply Helm
        run: terraform apply -target=module.helm -auto-approve

      - name: Terraform Plan K8s
        run: terraform plan -target=module.k8s

      - name: Terraform Apply K8s
        run: terraform apply -target=module.k8s -auto-approve
